### ISSUE TITLE
Features not working since Qud update 2019-08-10

### ISSUE THREAD

**Issue by SabreCat** [egocarib/CavesOfQud-QudUX#2] opened 2019-08-14 11:40 UTC
Since the latest Qud patch, I've noticed the following:

* The dialogue option used to highlight quest-giver NPCs is present, but when selected does nothing. No map highlight, no dialogue quip.
* Generic "Some forgotten ruins" still spawn and are referenced in village quests.

I don't see any relevant errors in player.log.

**Comment by egocarib** [comment] 2019-08-22 01:11
Thanks for the report, I just noticed this today too and I can reproduce it. I'll investigate in the coming days.

**Comment by egocarib** [comment] 2019-08-22 23:11
... and now it's working for me again today. 🤔

Will have to wait to see if I can reproduce it again.

**Comment by egocarib** [comment] 2019-09-17 17:48
Going to close this because I haven't seen the issue with quest-giver effects failing in about a month now. I think one of my previous commits may have fixed that (when I wrapped things in a try/catch block). 

I'm opening new issue #5 to track forgotten ruins naming specifically.

**Closed as completed by egocarib** 2019-09-17 17:48 UTC
Labels: bug
